"use client";

import { useState } from "react";
import {
  useAccount,
  useConnect,
  useDisconnect,
  useChainId,
  useSwitchChain,
  useDeployContract,
  useWaitForTransactionReceipt,
  useBalance,
} from "wagmi";
import { injected } from "wagmi/connectors";
import { ARC_TESTNET_CHAIN_ID, shortenAddress } from "@/lib/contract";
import { Logo } from "@/components/Logo";

// Compiled bytecode of EventProof.sol (OZ v4, Solidity 0.8.20)
// Generated by: npx hardhat compile
const CONTRACT_ABI = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "name",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "symbol",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
] as const;

export default function DeployPage() {
  const { address, isConnected } = useAccount();
  const { connect, isPending: isConnecting } = useConnect();
  const { disconnect } = useDisconnect();
  const chainId = useChainId();
  const { switchChain, isPending: isSwitching } = useSwitchChain();
  const [deployedAddress, setDeployedAddress] = useState<string | null>(null);
  const [bytecodeMissing, setBytecodeMissing] = useState(false);

  const { data: balance } = useBalance({ address });

  const isWrongNetwork = isConnected && chainId !== ARC_TESTNET_CHAIN_ID;

  const {
    deployContract,
    data: deployHash,
    isPending: isDeploying,
    error: deployError,
  } = useDeployContract();

  const { isLoading: isConfirming, isSuccess } = useWaitForTransactionReceipt({
    hash: deployHash,
  });

  async function handleDeploy() {
    // Load bytecode from artifacts
    let bytecode: `0x${string}`;
    try {
      const res = await fetch("/EventProof.json");
      if (!res.ok) throw new Error("not found");
      const artifact = await res.json();
      bytecode = artifact.bytecode as `0x${string}`;
    } catch {
      setBytecodeMissing(true);
      return;
    }

    deployContract({
      abi: CONTRACT_ABI,
      bytecode,
    });
  }

  // Copy contract address helper
  function copyAddress(addr: string) {
    navigator.clipboard.writeText(addr);
  }

  const step = !isConnected
    ? "connect"
    : isWrongNetwork
    ? "switch"
    : isSuccess && deployHash
    ? "done"
    : "deploy";

  return (
    <div className="min-h-screen flex items-center justify-center px-4">
      <div className="w-full max-w-lg">
        {/* Header */}
        <div className="text-center mb-10">
          <div className="inline-flex items-center justify-center mb-6">
            <Logo size={64} />
          </div>
          <h1 className="display text-4xl text-[var(--text-1)] mb-2">
            Deploy <span className="gold-text italic">EventProof</span>
          </h1>
          <p className="text-[var(--text-2)] font-light">
            Connect your wallet and deploy the EventProof smart contract to ARC Testnet.
            You will be the contract owner (photographer).
          </p>
        </div>

        {/* Steps progress */}
        <div className="flex items-center gap-2 mb-8">
          {["Connect", "Switch Network", "Deploy"].map((label, i) => {
            const stepKeys = ["connect", "switch", "deploy"];
            const stepIdx = ["connect", "switch", "deploy"].indexOf(step);
            const done = i < stepIdx || step === "done";
            const active = stepKeys[i] === step;
            return (
              <div key={label} className="flex items-center gap-2 flex-1">
                <div className={`flex items-center gap-2 ${i > 0 ? "flex-1" : ""}`}>
                  {i > 0 && <div className={`flex-1 h-px ${done ? "bg-[var(--gold-soft)]" : "bg-[var(--border)]"}`} />}
                  <div className={`w-7 h-7 rounded-full flex items-center justify-center text-xs font-bold transition-all ${
                    done ? "bg-[var(--gold)] text-[#15110a]" :
                    active ? "bg-[var(--gold-bg)] border-2 border-[var(--gold-soft)] text-[var(--gold)]" :
                    "bg-[var(--bg-2)] border border-[var(--border)] text-[var(--text-3)]"
                  }`}>
                    {done ? "✓" : i + 1}
                  </div>
                </div>
                <span className={`text-xs font-medium whitespace-nowrap ${active ? "text-[var(--text-1)]" : done ? "text-[var(--gold)]" : "text-[var(--text-3)]"}`}>
                  {label}
                </span>
              </div>
            );
          })}
        </div>

        {/* Main card */}
        <div className="card p-6 space-y-5">
          {/* Network info */}
          <div className="bg-[var(--bg-1)] rounded-sm p-4 border border-[var(--border)]">
            <div className="flex items-center justify-between text-sm">
              <span className="text-[var(--text-3)]">Target network</span>
              <span className="text-[var(--gold)] font-medium flex items-center gap-2">
                <span className="w-2 h-2 rounded-full bg-[var(--gold)] animate-pulse"></span>
                ARC Testnet (5042002)
              </span>
            </div>
            <div className="flex items-center justify-between text-sm mt-2">
              <span className="text-[var(--text-3)]">Contract</span>
              <span className="text-[var(--text-2)] font-mono">EventProof (EVPF)</span>
            </div>
            {isConnected && balance && (
              <div className="flex items-center justify-between text-sm mt-2">
                <span className="text-[var(--text-3)]">Your balance</span>
                <span className="text-[var(--text-2)] font-mono">
                  {parseFloat(balance.formatted).toFixed(4)} {balance.symbol}
                </span>
              </div>
            )}
          </div>

          {/* Step: Connect */}
          {!isConnected && (
            <button
              onClick={() => connect({ connector: injected() })}
              disabled={isConnecting}
              className="btn-primary w-full text-base py-4 flex items-center justify-center gap-3"
            >
              {isConnecting ? (
                <>
                  <svg className="animate-spin w-5 h-5" fill="none" viewBox="0 0 24 24">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"/>
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"/>
                  </svg>
                  Connecting…
                </>
              ) : (
                <>
                  <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" d="M21 12a2.25 2.25 0 00-2.25-2.25H15a3 3 0 11-6 0H5.25A2.25 2.25 0 003 12m18 0v6a2.25 2.25 0 01-2.25 2.25H5.25A2.25 2.25 0 013 18v-6m18 0V9M3 12V9m18-3a2.25 2.25 0 00-2.25-2.25H5.25A2.25 2.25 0 003 6" />
                  </svg>
                  Connect Wallet (MetaMask)
                </>
              )}
            </button>
          )}

          {/* Connected info */}
          {isConnected && address && (
            <div className="flex items-center justify-between bg-[var(--success-bg)] border border-[rgba(127,209,160,0.3)] rounded-sm px-4 py-3">
              <div className="flex items-center gap-2">
                <span className="w-2 h-2 rounded-full bg-[var(--success)]"></span>
                <span className="text-[var(--success)] text-sm font-medium">Connected</span>
                <span className="text-[var(--text-2)] text-sm font-mono">{shortenAddress(address)}</span>
              </div>
              <button onClick={() => disconnect()} className="text-[var(--text-3)] hover:text-[var(--gold)] text-xs transition-colors">
                Disconnect
              </button>
            </div>
          )}

          {/* Step: Switch network */}
          {isWrongNetwork && (
            <button
              onClick={() => switchChain({ chainId: ARC_TESTNET_CHAIN_ID })}
              disabled={isSwitching}
              className="btn-primary w-full text-base py-4 flex items-center justify-center gap-3"
            >
              {isSwitching ? (
                <>
                  <svg className="animate-spin w-5 h-5" fill="none" viewBox="0 0 24 24">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"/>
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"/>
                  </svg>
                  Switching…
                </>
              ) : (
                "⚡ Switch to ARC Testnet"
              )}
            </button>
          )}

          {/* Step: Deploy */}
          {isConnected && !isWrongNetwork && step !== "done" && (
            <>
              {bytecodeMissing && (
                <div className="bg-[var(--gold-bg)] border border-[rgba(217,178,79,0.3)] rounded-sm px-4 py-3 text-[var(--gold)] text-sm">
                  <p className="font-semibold mb-1">⚠ Bytecode not found</p>
                  <p>Compile the contract first:</p>
                  <code className="block mt-1 text-xs bg-black/30 rounded px-2 py-1">
                    cd EventProof && npm run compile
                  </code>
                  <p className="mt-1">Then copy <code className="text-xs">artifacts/contracts/EventProof.sol/EventProof.json</code> to <code className="text-xs">frontend/public/EventProof.json</code></p>
                </div>
              )}

              <button
                onClick={handleDeploy}
                disabled={isDeploying || isConfirming}
                className="btn-primary w-full text-base py-4 flex items-center justify-center gap-3"
              >
                {isDeploying ? (
                  <>
                    <svg className="animate-spin w-5 h-5" fill="none" viewBox="0 0 24 24">
                      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"/>
                      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"/>
                    </svg>
                    Confirm in MetaMask…
                  </>
                ) : isConfirming ? (
                  <>
                    <svg className="animate-spin w-5 h-5" fill="none" viewBox="0 0 24 24">
                      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"/>
                      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"/>
                    </svg>
                    Deploying on-chain…
                  </>
                ) : (
                  <>
                    <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5M16.5 12L12 16.5m0 0L7.5 12m4.5 4.5V3" />
                    </svg>
                    Deploy EventProof Contract
                  </>
                )}
              </button>

              {deployError && (
                <div className="bg-[var(--danger-bg)] border border-[rgba(224,138,130,0.3)] rounded-sm px-4 py-3 text-[var(--danger)] text-sm">
                  {deployError.message.slice(0, 300)}
                </div>
              )}
            </>
          )}

          {/* Done! */}
          {isSuccess && deployHash && (
            <div className="space-y-4 animate-fade-in">
              <div className="bg-[var(--success-bg)] border border-[rgba(127,209,160,0.3)] rounded-sm p-5 text-center">
                <div className="text-3xl mb-3 text-[var(--gold)]">✦</div>
                <h3 className="display text-xl text-[var(--success)] mb-1">Contract Deployed!</h3>
                <p className="text-[var(--text-3)] text-sm">EventProof is live on ARC Testnet</p>
              </div>

              <div className="bg-[var(--bg-1)] rounded-sm p-4 border border-[var(--border)] space-y-3">
                <div>
                  <p className="text-[var(--text-3)] text-xs mb-1">Transaction hash</p>
                  <div className="flex items-center gap-2">
                    <code className="text-[var(--gold)] text-xs font-mono flex-1 truncate">{deployHash}</code>
                    <a
                      href={`https://testnet.arcscan.app/tx/${deployHash}`}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="text-[var(--gold)] text-xs hover:underline flex-shrink-0"
                    >
                      View ↗
                    </a>
                  </div>
                </div>
              </div>

              <div className="bg-[var(--gold-bg)] border border-[rgba(217,178,79,0.3)] rounded-sm p-4">
                <p className="text-[var(--text-2)] text-sm font-semibold mb-2">Next step</p>
                <p className="text-[var(--text-3)] text-xs mb-3">
                  Copy the contract address from ArcScan and paste it into{" "}
                  <code className="text-[var(--gold)]">frontend/.env.local</code>:
                </p>
                <code className="block text-xs bg-black/30 rounded px-3 py-2 text-[var(--gold)] break-all">
                  NEXT_PUBLIC_CONTRACT_ADDRESS={"<contract address from ArcScan>"}
                </code>
                <a
                  href={`https://testnet.arcscan.app/tx/${deployHash}`}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center gap-2 mt-3 btn-secondary text-sm py-2 w-full justify-center"
                >
                  Open on ArcScan to get contract address ↗
                </a>
              </div>

              <a href="/" className="btn-primary w-full text-center block py-3">
                Go to Gallery →
              </a>
            </div>
          )}
        </div>

        <p className="text-center text-[var(--text-3)] text-xs mt-6">
          This page is for one-time contract deployment only.
          After deploying, use the main gallery at{" "}
          <a href="/" className="text-[var(--gold)] hover:underline">localhost:3002</a>
        </p>
      </div>
    </div>
  );
}
