"use client";

import { useState } from "react";
import {
  useAccount,
  useConnect,
  useDisconnect,
  useChainId,
  useSwitchChain,
  useDeployContract,
  useWaitForTransactionReceipt,
  useBalance,
} from "wagmi";
import { injected } from "wagmi/connectors";
import { ARC_TESTNET_CHAIN_ID, shortenAddress } from "@/lib/contract";

// Compiled bytecode of EventProof.sol (OZ v4, Solidity 0.8.20)
// Generated by: npx hardhat compile
const CONTRACT_ABI = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "name",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "symbol",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
] as const;

export default function DeployPage() {
  const { address, isConnected } = useAccount();
  const { connect, isPending: isConnecting } = useConnect();
  const { disconnect } = useDisconnect();
  const chainId = useChainId();
  const { switchChain, isPending: isSwitching } = useSwitchChain();
  const [deployedAddress, setDeployedAddress] = useState<string | null>(null);
  const [bytecodeMissing, setBytecodeMissing] = useState(false);

  const { data: balance } = useBalance({ address });

  const isWrongNetwork = isConnected && chainId !== ARC_TESTNET_CHAIN_ID;

  const {
    deployContract,
    data: deployHash,
    isPending: isDeploying,
    error: deployError,
  } = useDeployContract();

  const { isLoading: isConfirming, isSuccess } = useWaitForTransactionReceipt({
    hash: deployHash,
  });

  async function handleDeploy() {
    // Load bytecode from artifacts
    let bytecode: `0x${string}`;
    try {
      const res = await fetch("/EventProof.json");
      if (!res.ok) throw new Error("not found");
      const artifact = await res.json();
      bytecode = artifact.bytecode as `0x${string}`;
    } catch {
      setBytecodeMissing(true);
      return;
    }

    deployContract({
      abi: CONTRACT_ABI,
      bytecode,
    });
  }

  // Copy contract address helper
  function copyAddress(addr: string) {
    navigator.clipboard.writeText(addr);
  }

  const step = !isConnected
    ? "connect"
    : isWrongNetwork
    ? "switch"
    : isSuccess && deployHash
    ? "done"
    : "deploy";

  return (
    <div className="min-h-screen flex items-center justify-center px-4">
      <div className="w-full max-w-lg">
        {/* Header */}
        <div className="text-center mb-10">
          <div className="inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-gradient-to-br from-arc-400 to-arc-700 shadow-2xl shadow-arc-600/40 mb-6">
            <svg viewBox="0 0 24 24" fill="none" className="w-8 h-8 text-white" strokeWidth={1.5} stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" d="M6.827 6.175A2.31 2.31 0 015.186 7.23c-.38.054-.757.112-1.134.175C2.999 7.58 2.25 8.507 2.25 9.574V18a2.25 2.25 0 002.25 2.25h15A2.25 2.25 0 0021.75 18V9.574c0-1.067-.75-1.994-1.802-2.169a47.865 47.865 0 00-1.134-.175 2.31 2.31 0 01-1.64-1.055l-.822-1.316a2.192 2.192 0 00-1.736-1.039 48.774 48.774 0 00-5.232 0 2.192 2.192 0 00-1.736 1.039l-.821 1.316z" />
              <path strokeLinecap="round" strokeLinejoin="round" d="M16.5 12.75a4.5 4.5 0 11-9 0 4.5 4.5 0 019 0zM18.75 10.5h.008v.008h-.008V10.5z" />
            </svg>
          </div>
          <h1 className="text-3xl font-bold text-white mb-2">Deploy EventProof</h1>
          <p className="text-white/50">
            Connect your wallet and deploy the EventProof smart contract to ARC Testnet.
            You will be the contract owner (photographer).
          </p>
        </div>

        {/* Steps progress */}
        <div className="flex items-center gap-2 mb-8">
          {["Connect", "Switch Network", "Deploy"].map((label, i) => {
            const stepKeys = ["connect", "switch", "deploy"];
            const stepIdx = ["connect", "switch", "deploy"].indexOf(step);
            const done = i < stepIdx || step === "done";
            const active = stepKeys[i] === step;
            return (
              <div key={label} className="flex items-center gap-2 flex-1">
                <div className={`flex items-center gap-2 ${i > 0 ? "flex-1" : ""}`}>
                  {i > 0 && <div className={`flex-1 h-px ${done ? "bg-arc-500" : "bg-white/10"}`} />}
                  <div className={`w-7 h-7 rounded-full flex items-center justify-center text-xs font-bold transition-all ${
                    done ? "bg-arc-600 text-white" :
                    active ? "bg-arc-600/30 border-2 border-arc-500 text-arc-300" :
                    "bg-white/5 border border-white/10 text-white/30"
                  }`}>
                    {done ? "✓" : i + 1}
                  </div>
                </div>
                <span className={`text-xs font-medium whitespace-nowrap ${active ? "text-white" : done ? "text-arc-400" : "text-white/30"}`}>
                  {label}
                </span>
              </div>
            );
          })}
        </div>

        {/* Main card */}
        <div className="card p-6 space-y-5">
          {/* Network info */}
          <div className="bg-white/5 rounded-xl p-4 border border-white/10">
            <div className="flex items-center justify-between text-sm">
              <span className="text-white/40">Target network</span>
              <span className="text-arc-300 font-medium flex items-center gap-2">
                <span className="w-2 h-2 rounded-full bg-arc-400 animate-pulse"></span>
                ARC Testnet (5042002)
              </span>
            </div>
            <div className="flex items-center justify-between text-sm mt-2">
              <span className="text-white/40">Contract</span>
              <span className="text-white/70 font-mono">EventProof (EVPF)</span>
            </div>
            {isConnected && balance && (
              <div className="flex items-center justify-between text-sm mt-2">
                <span className="text-white/40">Your balance</span>
                <span className="text-white/70 font-mono">
                  {parseFloat(balance.formatted).toFixed(4)} {balance.symbol}
                </span>
              </div>
            )}
          </div>

          {/* Step: Connect */}
          {!isConnected && (
            <button
              onClick={() => connect({ connector: injected() })}
              disabled={isConnecting}
              className="btn-primary w-full text-base py-4 flex items-center justify-center gap-3"
            >
              {isConnecting ? (
                <>
                  <svg className="animate-spin w-5 h-5" fill="none" viewBox="0 0 24 24">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"/>
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"/>
                  </svg>
                  Connecting…
                </>
              ) : (
                <>
                  <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" d="M21 12a2.25 2.25 0 00-2.25-2.25H15a3 3 0 11-6 0H5.25A2.25 2.25 0 003 12m18 0v6a2.25 2.25 0 01-2.25 2.25H5.25A2.25 2.25 0 013 18v-6m18 0V9M3 12V9m18-3a2.25 2.25 0 00-2.25-2.25H5.25A2.25 2.25 0 003 6" />
                  </svg>
                  Connect Wallet (MetaMask)
                </>
              )}
            </button>
          )}

          {/* Connected info */}
          {isConnected && address && (
            <div className="flex items-center justify-between bg-emerald-500/10 border border-emerald-500/30 rounded-xl px-4 py-3">
              <div className="flex items-center gap-2">
                <span className="w-2 h-2 rounded-full bg-emerald-400"></span>
                <span className="text-emerald-400 text-sm font-medium">Connected</span>
                <span className="text-white/60 text-sm font-mono">{shortenAddress(address)}</span>
              </div>
              <button onClick={() => disconnect()} className="text-white/40 hover:text-white/70 text-xs transition-colors">
                Disconnect
              </button>
            </div>
          )}

          {/* Step: Switch network */}
          {isWrongNetwork && (
            <button
              onClick={() => switchChain({ chainId: ARC_TESTNET_CHAIN_ID })}
              disabled={isSwitching}
              className="btn-primary w-full text-base py-4 flex items-center justify-center gap-3 bg-amber-600 hover:bg-amber-500"
            >
              {isSwitching ? (
                <>
                  <svg className="animate-spin w-5 h-5" fill="none" viewBox="0 0 24 24">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"/>
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"/>
                  </svg>
                  Switching…
                </>
              ) : (
                "⚡ Switch to ARC Testnet"
              )}
            </button>
          )}

          {/* Step: Deploy */}
          {isConnected && !isWrongNetwork && step !== "done" && (
            <>
              {bytecodeMissing && (
                <div className="bg-amber-500/10 border border-amber-500/30 rounded-xl px-4 py-3 text-amber-400 text-sm">
                  <p className="font-semibold mb-1">⚠ Bytecode not found</p>
                  <p>Compile the contract first:</p>
                  <code className="block mt-1 text-xs bg-black/30 rounded px-2 py-1">
                    cd EventProof && npm run compile
                  </code>
                  <p className="mt-1">Then copy <code className="text-xs">artifacts/contracts/EventProof.sol/EventProof.json</code> to <code className="text-xs">frontend/public/EventProof.json</code></p>
                </div>
              )}

              <button
                onClick={handleDeploy}
                disabled={isDeploying || isConfirming}
                className="btn-primary w-full text-base py-4 flex items-center justify-center gap-3"
              >
                {isDeploying ? (
                  <>
                    <svg className="animate-spin w-5 h-5" fill="none" viewBox="0 0 24 24">
                      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"/>
                      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"/>
                    </svg>
                    Confirm in MetaMask…
                  </>
                ) : isConfirming ? (
                  <>
                    <svg className="animate-spin w-5 h-5" fill="none" viewBox="0 0 24 24">
                      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"/>
                      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"/>
                    </svg>
                    Deploying on-chain…
                  </>
                ) : (
                  <>
                    <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5M16.5 12L12 16.5m0 0L7.5 12m4.5 4.5V3" />
                    </svg>
                    Deploy EventProof Contract
                  </>
                )}
              </button>

              {deployError && (
                <div className="bg-red-500/10 border border-red-500/30 rounded-xl px-4 py-3 text-red-400 text-sm">
                  {deployError.message.slice(0, 300)}
                </div>
              )}
            </>
          )}

          {/* Done! */}
          {isSuccess && deployHash && (
            <div className="space-y-4 animate-fade-in">
              <div className="bg-emerald-500/10 border border-emerald-500/30 rounded-xl p-5 text-center">
                <div className="text-4xl mb-3">🎉</div>
                <h3 className="text-xl font-bold text-emerald-400 mb-1">Contract Deployed!</h3>
                <p className="text-white/50 text-sm">EventProof is live on ARC Testnet</p>
              </div>

              <div className="bg-white/5 rounded-xl p-4 border border-white/10 space-y-3">
                <div>
                  <p className="text-white/40 text-xs mb-1">Transaction hash</p>
                  <div className="flex items-center gap-2">
                    <code className="text-arc-300 text-xs font-mono flex-1 truncate">{deployHash}</code>
                    <a
                      href={`https://testnet.arcscan.app/tx/${deployHash}`}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="text-arc-400 text-xs hover:underline flex-shrink-0"
                    >
                      View ↗
                    </a>
                  </div>
                </div>
              </div>

              <div className="bg-arc-600/10 border border-arc-500/30 rounded-xl p-4">
                <p className="text-white/60 text-sm font-semibold mb-2">📋 Next step:</p>
                <p className="text-white/50 text-xs mb-3">
                  Copy the contract address from ArcScan and paste it into{" "}
                  <code className="text-arc-400">frontend/.env.local</code>:
                </p>
                <code className="block text-xs bg-black/30 rounded px-3 py-2 text-arc-300 break-all">
                  NEXT_PUBLIC_CONTRACT_ADDRESS={"<contract address from ArcScan>"}
                </code>
                <a
                  href={`https://testnet.arcscan.app/tx/${deployHash}`}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center gap-2 mt-3 btn-secondary text-sm py-2 w-full justify-center"
                >
                  Open on ArcScan to get contract address ↗
                </a>
              </div>

              <a href="/" className="btn-primary w-full text-center block py-3">
                Go to Gallery →
              </a>
            </div>
          )}
        </div>

        <p className="text-center text-white/20 text-xs mt-6">
          This page is for one-time contract deployment only.
          After deploying, use the main gallery at{" "}
          <a href="/" className="text-arc-400 hover:underline">localhost:3002</a>
        </p>
      </div>
    </div>
  );
}
